import { Metadata } from 'next';

import '../globals.scss';
import AppProvider from 'src/app/(main)/components/providers';
import Footer from 'components/Footer/Footer';
import CookiesPanel from 'components/Cookies/CookiesPanel';
import { ReactNode } from 'react';
import Header from '@/app/(main)/components/Header/Header';

export const metadata: Metadata = {
  title: 'Читозаврик',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => (
  <AppProvider>
    <Header />
    {children}
    <Footer />
    <CookiesPanel />
  </AppProvider>
);

export default RootLayout;
