export enum Route {
  HOME = '/',
  SIGN_UP = '/?auth=signup',
  SIGN_UP_SUCCESS = '/?auth=signup-success',
  SIGN_IN = '/?auth=signin',
  FORGOT_PASSWORD = '/auth=forgot-password',
  RESET_PASSWORD = '/?auth=reset-password',
  NEW_PASSWORD = '/?auth=new-password',
  WIGWAM = '/wigwam',
  WIGWAM_LOBBY = '/parents/lobby',
  PARENTS = '/parents',
  USERS = '/admin',
  BOOKS = '/admin/books',
  QUIZZES = '/admin/quizzes',
  RECOMMENDED = '/admin/recommended',
  DOCUMENTS = '/admin/documents',
  PARTNERS = '/admin/partners',
  CONTACTS = '/admin/contacts',
  STATS = '/admin/statistics',
  CHANGE_PASS = '/admin/password',
}
