'use client';
import { Metadata } from 'next';
import { Raleway, Montserrat_Alternates } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '../components/Footer/Footer';
import AppProvider from '@/components/providers';
import './globals.scss';
import { usePathname } from 'next/navigation';
import { useState, useEffect } from 'react';
import Navbar from '@/components/Navbar/Navbar';
import NavbarMob from '@/components/NavbarMob/NavbarMob';

const raleway = Raleway({
  variable: '--raleway-font',
  weight: ['300', '400', '500', '800'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
});

const montserratAlternates = Montserrat_Alternates({
  variable: '--montserrat-alternates-font',
  weight: ['400', '600'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
});

// export const metadata: Metadata = {
//   title: 'Читозаврик',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const router = usePathname();

  const [navBarVisible, setNavBarVisible] = useState(true);
  const [headerVisible, setHeaderVisible] = useState(true);

  useEffect(() => {
    function handleResize() {
      if (window.innerWidth <= 767) {
        setNavBarVisible(false);
        setHeaderVisible(true);
      } else {
        setNavBarVisible(true);
        setHeaderVisible(false);
      }
    }

    window.addEventListener('resize', handleResize);

    handleResize();

    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []);

  return (
    <html lang="uk" className={`${raleway.variable} ${montserratAlternates.variable}`}>
      <body>
        <AppProvider>
          {router === '/' || router === '/parents' ? (
            <Header />
          ) : (
            <div>
              {navBarVisible && <Navbar />}
              {headerVisible && <NavbarMob />}
            </div>
          )}
          {children}

          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
