import { Metadata } from 'next';
import Header from '@/components/Header';
import { Raleway, Montserrat_Alternates } from 'next/font/google';
import './globals.scss';

const raleway = Raleway({
  variable: '--raleway-font',
  weight: ['300', '800'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
});

const montserratAlternates = Montserrat_Alternates({
  variable: '--montserrat-alternates-font',
  weight: '600',
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Читозаврик',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="uk" className={`${raleway.variable} ${montserratAlternates.variable}`}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
